apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: smar-vaultkubenertes-job
  namespace: smar-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: smar-vaultkubenertes-job
  chart:
    git: https://github.com/mgCepeda/blockchain-automation-framework.git
    ref: feature-1429
    path: platforms/hyperledger-fabric/charts/vault_kubernetes
    secretRef:
      name: gitcredentials
  values:
    metadata:
      name: smar
      component_type: orderer
      namespace: smar-net    
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      reviewer_service: vault-reviewer
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: marsmar-net-auth
      policy: vault-crypto-orderer-smar-net-ro
      secret_path: secretsv2
      serviceaccountname: vault-auth
      imagesecretname: regcred
    
    k8s:
      kubernetes_url: https://C8FA1454BFC54EBEAC7D6A70501769F2.sk1.eu-west-1.eks.amazonaws.com
