apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: smari-net-ca-tools
  namespace: smari-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: smari-net-ca-tools
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-mar
        namespace: flux-mar
      chart: platforms/hyperledger-fabric/charts/fabric-catools
  values:
    metadata:
      namespace: smari-net
      name: ca-tools
      component_type: orderer
      org_name: smari
      proxy: haproxy
    replicaCount: 1

    image:
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      catools: ghcr.io/hyperledger/bevel-fabric-ca-tools:1.2.1
      pullPolicy: IfNotPresent
    
    storage:
      storageclassname: smari-bevel-storageclass
      storagesize: 512Mi
    
    vault:
      role: vault-role
      address: http://98.64.226.131:20001
      authpath: marsmari
      secretusers: secretsv2/data/smari/ordererOrganizations/smari-net/users
      secretorderer: secretsv2/data/smari/ordererOrganizations/smari-net/orderers
      secretpeer: secretsv2/data/smari/ordererOrganizations/smari-net/peers
      secretpeerorderertls: secretsv2/data/smari/ordererOrganizations/smari-net/orderer/tls
      secretcert: secretsv2/data/smari/ordererOrganizations/smari-net/ca?ca.smari-net-cert.pem
      secretkey: secretsv2/data/smari/ordererOrganizations/smari-net/ca?smari-net-CA.key
      secretcouchdb: secretsv2/data/smari/credentials/smari-net/couchdb/smari
      secretconfigfile: secretsv2/data/smari/ordererOrganizations/smari-net/msp/config
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: ""
    
    healthcheck: 
      retries: 10
      sleepTimeAfterError: 2

    
    org_data:
      external_url_suffix: hlf.blockchaincloudpoc-develop.com
      component_subject: O=Orderer,L=51.50/-0.13/London,C=GB
      cert_subject: O=Orderer/L=51.50,-0.13,London/C=GB
      component_country: UK
      component_state: London
      component_location: London
      ca_url: ca.smari-net:7054

    orderers:
      name: orderer1-orderer2-
