apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: smari-cacerts-job
  namespace: smari-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: smari-cacerts-job
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-mar
        namespace: flux-mar
      chart: platforms/hyperledger-fabric/charts/fabric-cacerts-gen
  values:
    metadata:
      name: smari
      component_name: smari-net
      namespace: smari-net    
      images:
       alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
    vault:
      role: vault-role
      address: http://98.64.226.131:20001
      authpath: marsmari
      secretcryptoprefix: secretsv2/data/smari/ordererOrganizations/smari-net/ca
      secretcredentialsprefix: secretsv2/data/smari/credentials/smari-net/ca/smari
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: ""
      
    ca:
      subject: /C=GB/ST=London/L=London/O=Orderer/CN=ca.smari-net
