apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cmari-net-ca-tools
  namespace: cmari-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: cmari-net-ca-tools
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-mar
        namespace: flux-mar
      chart: platforms/hyperledger-fabric/charts/fabric-catools
  values:
    metadata:
      namespace: cmari-net
      name: ca-tools
      component_type: peer
      org_name: cmari
      proxy: haproxy
    replicaCount: 1

    image:
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      catools: ghcr.io/hyperledger/bevel-fabric-ca-tools:1.2.1
      pullPolicy: IfNotPresent
    
    storage:
      storageclassname: cmari-bevel-storageclass
      storagesize: 512Mi
    
    vault:
      role: vault-role
      address: http://98.64.226.131:20001
      authpath: marcmari
      secretusers: secretsv2/data/cmari/peerOrganizations/cmari-net/users
      secretorderer: secretsv2/data/cmari/peerOrganizations/cmari-net/orderers
      secretpeer: secretsv2/data/cmari/peerOrganizations/cmari-net/peers
      secretpeerorderertls: secretsv2/data/cmari/peerOrganizations/cmari-net/orderer/tls
      secretcert: secretsv2/data/cmari/peerOrganizations/cmari-net/ca?ca.cmari-net-cert.pem
      secretkey: secretsv2/data/cmari/peerOrganizations/cmari-net/ca?cmari-net-CA.key
      secretcouchdb: secretsv2/data/cmari/credentials/cmari-net/couchdb/cmari
      secretconfigfile: secretsv2/data/cmari/peerOrganizations/cmari-net/msp/config
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: ""
    
    healthcheck: 
      retries: 10
      sleepTimeAfterError: 2

    
    org_data:
      external_url_suffix: hlf.blockchaincloudpoc-develop.com
      component_subject: O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB
      cert_subject: O=Carrier/OU=Carrier/L=51.50,-0.13,London/C=GB
      component_country: GB
      component_state: London
      component_location: London
      ca_url: ca.cmari-net:7054

    orderers:
      name: orderer1-orderer2-
    orderers_info:
      - name: orderer1
        path: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI5RENDQVpxZ0F3SUJBZ0lVWEFtVFRFOVdqaTJ6dUZhL0JRcWV3Y0FFUmI0d0NnWUlLb1pJemowRUF3SXcKV0RFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUlV3RXdZRFZRUUREQXhqWVM1emJXRnlhUzF1WlhRd0hoY05NalF3Ck56RTJNRGN4TkRJeVdoY05NamN3TlRBMk1EY3hOREl5V2pCWU1Rc3dDUVlEVlFRR0V3SkhRakVQTUEwR0ExVUUKQ0F3R1RHOXVaRzl1TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnlaWEl4RlRBVApCZ05WQkFNTURHTmhMbk50WVhKcExXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCR2FqCmMxN0RKVDZZQndVMGlBWi9YbEg0UHZoeVdpb3Nvc0RwekU4OFp6WnNHb1ZIUlNtQnZDdWZ6bUpKa1RGdlordW4KQnhkcU1rbTNodGc0aFJpMG05R2pRakJBTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRRApBZ0dtTUIwR0ExVWREZ1FXQkJUZ1JYaHlJUzNVbHRpTzhLSjhTSGlicHlBdEZUQUtCZ2dxaGtqT1BRUURBZ05JCkFEQkZBaUVBN2JLeVRibUtkKzBmMWNPMGlDcG1EanRCL2pNMXZqaDlOS25rcXRYaTE1b0NJR1hVSHZjbGtET3AKckJrMitZZm93VnFwak5TVnlRQk9FNHlnSnVwTXFKRWQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ=="
      - name: orderer2
        path: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI5RENDQVpxZ0F3SUJBZ0lVWEFtVFRFOVdqaTJ6dUZhL0JRcWV3Y0FFUmI0d0NnWUlLb1pJemowRUF3SXcKV0RFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUlV3RXdZRFZRUUREQXhqWVM1emJXRnlhUzF1WlhRd0hoY05NalF3Ck56RTJNRGN4TkRJeVdoY05NamN3TlRBMk1EY3hOREl5V2pCWU1Rc3dDUVlEVlFRR0V3SkhRakVQTUEwR0ExVUUKQ0F3R1RHOXVaRzl1TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnlaWEl4RlRBVApCZ05WQkFNTURHTmhMbk50WVhKcExXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCR2FqCmMxN0RKVDZZQndVMGlBWi9YbEg0UHZoeVdpb3Nvc0RwekU4OFp6WnNHb1ZIUlNtQnZDdWZ6bUpKa1RGdlordW4KQnhkcU1rbTNodGc0aFJpMG05R2pRakJBTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRRApBZ0dtTUIwR0ExVWREZ1FXQkJUZ1JYaHlJUzNVbHRpTzhLSjhTSGlicHlBdEZUQUtCZ2dxaGtqT1BRUURBZ05JCkFEQkZBaUVBN2JLeVRibUtkKzBmMWNPMGlDcG1EanRCL2pNMXZqaDlOS25rcXRYaTE1b0NJR1hVSHZjbGtET3AKckJrMitZZm93VnFwak5TVnlRQk9FNHlnSnVwTXFKRWQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ=="

    peers:
      name: peer0,-      
    peer_count: "1"
    users: 
      users_list: "W3sndXNlcic6IE5vbmUsICdpZGVudGl0eSc6ICd1c2VyMScsICdhdHRyaWJ1dGVzJzogW3sna2V5JzogJ2hmLlJldm9rZXInLCAndmFsdWUnOiAndHJ1ZSd9XX0sIHsndXNlcic6IE5vbmUsICdpZGVudGl0eSc6ICd1c2VyMicsICdhdHRyaWJ1dGVzJzogW3sna2V5JzogJ2hmLlJldm9rZXInLCAndmFsdWUnOiAndHJ1ZSd9XX1d"
      users_identities: user1-user2-
    checks:
      refresh_cert_value: False
      refresh_user_cert_value: False
      add_peer_value: False
