apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cmari-net-ca
  namespace: cmari-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: cmari-net-ca
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-mar
        namespace: flux-mar
      chart: platforms/hyperledger-fabric/charts/fabric-ca-server  
  values:
    metadata:
      namespace: cmari-net
      images:
        alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
        ca: ghcr.io/hyperledger/bevel-fabric-ca:latest
 
    server:
      name: ca
      tlsstatus: true
      admin: cmari-admin 
  
    storage:
      storageclassname: cmari-bevel-storageclass
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://98.64.226.131:20001
      authpath: marcmari
      secretcert: secretsv2/data/cmari/peerOrganizations/cmari-net/ca?ca.cmari-net-cert.pem
      secretkey: secretsv2/data/cmari/peerOrganizations/cmari-net/ca?cmari-net-CA.key
      secretadminpass: secretsv2/data/cmari/credentials/cmari-net/ca/cmari?user
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: ""
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          clusteripport: 7054
    proxy:
      provider: haproxy
      type: peer
      external_url_suffix: hlf.blockchaincloudpoc-develop.com
