apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cmari-ca
  namespace: cmari-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: cmari-ca
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-mari
        namespace: flux-mari
      chart: platforms/hyperledger-fabric/charts/fabric-ca-server   
  values:
    global:
      serviceAccountName: vault-auth
      cluster:
        provider: azure
        cloudNativeServices: false
        kubernetesUrl: https://devcluster-devresourcegroup-d1d33f-kncld871.hcp.westeurope.azmk8s.io:443
      vault:
        type: hashicorp
        network: fabric
        address: http://98.64.226.131:20001
        authPath: maricmari
        secretEngine: secretsv2
        secretPrefix: "data/maricmari"
        role: vault-role
        tls: false
      proxy:
        provider: haproxy
        externalUrlSuffix: hlf.blockchaincloudpoc-develop.com

    storage:
      size: 512Mi
      reclaimPolicy: "Delete"
      volumeBindingMode: Immediate
      allowedTopologies:
        enabled: false

    image:
      alpineUtils: ghcr.io/hyperledger/bevel-alpine:latest
      ca: ghcr.io/hyperledger/bevel-fabric-ca:latest
      pullSecret: ""

    server:
      removeCertsOnDelete: true
      tlsStatus: true
      adminUsername: cmari-admin
      adminPassword: cmari-adminpw
      subject: "/C=GB/ST=London/L=London/O=Carrier"
      clusterIpPort: 7054

