apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wmari-net-ca-tools
  namespace: wmari-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: wmari-net-ca-tools
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-mar
        namespace: flux-mar
      chart: platforms/hyperledger-fabric/charts/fabric-catools
  values:
    metadata:
      namespace: wmari-net
      name: ca-tools
      component_type: peer
      org_name: wmari
      proxy: haproxy
    replicaCount: 1

    image:
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      catools: ghcr.io/hyperledger/bevel-fabric-ca-tools:1.2.1
      pullPolicy: IfNotPresent
    
    storage:
      storageclassname: wmari-bevel-storageclass
      storagesize: 512Mi
    
    vault:
      role: vault-role
      address: http://98.64.226.131:20001
      authpath: marwmari
      secretusers: secretsv2/data/wmari/peerOrganizations/wmari-net/users
      secretorderer: secretsv2/data/wmari/peerOrganizations/wmari-net/orderers
      secretpeer: secretsv2/data/wmari/peerOrganizations/wmari-net/peers
      secretpeerorderertls: secretsv2/data/wmari/peerOrganizations/wmari-net/orderer/tls
      secretcert: secretsv2/data/wmari/peerOrganizations/wmari-net/ca?ca.wmari-net-cert.pem
      secretkey: secretsv2/data/wmari/peerOrganizations/wmari-net/ca?wmari-net-CA.key
      secretcouchdb: secretsv2/data/wmari/credentials/wmari-net/couchdb/wmari
      secretconfigfile: secretsv2/data/wmari/peerOrganizations/wmari-net/msp/config
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: ""
    
    healthcheck: 
      retries: 10
      sleepTimeAfterError: 2

    
    org_data:
      external_url_suffix: hlf.blockchaincloudpoc-develop.com
      component_subject: O=Warehouse,OU=Warehouse,L=51.50/-0.13/London,C=GB
      cert_subject: O=Warehouse/OU=Warehouse/L=51.50,-0.13,London/C=GB
      component_country: GB
      component_state: London
      component_location: London
      ca_url: ca.wmari-net:7054

    orderers:
      name: orderer1-orderer2-
    orderers_info:
      - name: orderer1
        path: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI5VENDQVpxZ0F3SUJBZ0lVZjIxcW9CM2x1TUNEK1lMbjdnWnJGTDl0Vitnd0NnWUlLb1pJemowRUF3SXcKV0RFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUlV3RXdZRFZRUUREQXhqWVM1emJXRnlhUzF1WlhRd0hoY05NalF3Ck56RTRNRFl4TXpNNFdoY05NamN3TlRBNE1EWXhNek00V2pCWU1Rc3dDUVlEVlFRR0V3SkhRakVQTUEwR0ExVUUKQ0F3R1RHOXVaRzl1TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnlaWEl4RlRBVApCZ05WQkFNTURHTmhMbk50WVhKcExXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCRjAzCkxvMVhWWmM3aUhxU1o2bEl1MlJEbVNKaGRWUUduTlR4N000cll4b3RUcUx0aDU5eG5icmU3N3ozbzZ4UGwrcFIKaEY4Rk43V2tsL1YxRmRTb2xQeWpRakJBTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRRApBZ0dtTUIwR0ExVWREZ1FXQkJTdkorM3dZU05nNVJLeSt2emV0aWJoV0xDSmNqQUtCZ2dxaGtqT1BRUURBZ05KCkFEQkdBaUVBallIelNyRXlHVGVYZFFHY0xDM0hNZjh5OExRV2xPY2dabmhMRi9zY0xqSUNJUUNNV3RieXBTOUcKbDNDOUI1dDhxVk5iRUZTUWU1SkxYN0gvaXUxT2NzN2Q0Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0="
      - name: orderer2
        path: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI5VENDQVpxZ0F3SUJBZ0lVZjIxcW9CM2x1TUNEK1lMbjdnWnJGTDl0Vitnd0NnWUlLb1pJemowRUF3SXcKV0RFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUlV3RXdZRFZRUUREQXhqWVM1emJXRnlhUzF1WlhRd0hoY05NalF3Ck56RTRNRFl4TXpNNFdoY05NamN3TlRBNE1EWXhNek00V2pCWU1Rc3dDUVlEVlFRR0V3SkhRakVQTUEwR0ExVUUKQ0F3R1RHOXVaRzl1TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnlaWEl4RlRBVApCZ05WQkFNTURHTmhMbk50WVhKcExXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCRjAzCkxvMVhWWmM3aUhxU1o2bEl1MlJEbVNKaGRWUUduTlR4N000cll4b3RUcUx0aDU5eG5icmU3N3ozbzZ4UGwrcFIKaEY4Rk43V2tsL1YxRmRTb2xQeWpRakJBTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRRApBZ0dtTUIwR0ExVWREZ1FXQkJTdkorM3dZU05nNVJLeSt2emV0aWJoV0xDSmNqQUtCZ2dxaGtqT1BRUURBZ05KCkFEQkdBaUVBallIelNyRXlHVGVYZFFHY0xDM0hNZjh5OExRV2xPY2dabmhMRi9zY0xqSUNJUUNNV3RieXBTOUcKbDNDOUI1dDhxVk5iRUZTUWU1SkxYN0gvaXUxT2NzN2Q0Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0="

    peers:
      name: peer0,-      
    peer_count: "1"
    users: 
      users_list: "W3sndXNlcic6IE5vbmUsICdpZGVudGl0eSc6ICd1c2VyMScsICdhdHRyaWJ1dGVzJzogW3sna2V5JzogJ2hmLlJldm9rZXInLCAndmFsdWUnOiAndHJ1ZSd9XX0sIHsndXNlcic6IE5vbmUsICdpZGVudGl0eSc6ICd1c2VyMicsICdhdHRyaWJ1dGVzJzogW3sna2V5JzogJ2hmLlJldm9rZXInLCAndmFsdWUnOiAndHJ1ZSd9XX1d"
      users_identities: user1-user2-
    checks:
      refresh_cert_value: False
      refresh_user_cert_value: False
      add_peer_value: False
