##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-cli-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "fabric-cli.name" . }}-job
    app.kubernetes.io/component: cli
    app.kubernetes.io/part-of: {{ include "fabric-cli.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
    {{ include "labels.pvc" . | nindent 4 }}
spec:
  {{- if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass }}
  {{- else }}
  storageClassName: storage-{{ .Release.Name }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}
