apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: peer0-cmari-cli
  namespace: cmari-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: peer0-cmari-cli
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-mar
        namespace: flux-mar
      chart: platforms/hyperledger-fabric/charts/fabric-cli    
  values:
    metadata:
      namespace: cmari-net
      images:
        fabrictools: ghcr.io/hyperledger/bevel-fabric-tools:2.5.4
        alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
    storage:
      class: cmari-bevel-storageclass
      size: 256Mi
    vault:
      role: vault-role
      address: http://98.64.226.131:20001
      authpath: marcmari
      adminsecretprefix: secretsv2/data/cmari/peerOrganizations/cmari-net/users/admin
      orderersecretprefix: secretsv2/data/cmari/peerOrganizations/cmari-net/orderer
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: ""
      tls: false
    peer:
      name: peer0
      localmspid: cmariMSP
      tlsstatus: true
      address: peer0.cmari-net.hlf.blockchaincloudpoc-develop.com:443
    orderer:
      address: orderer1.hlf.blockchaincloudpoc-develop.com:443
