apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: smar-vaultk8s-job
  namespace: smar-bes
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: smar-vaultk8s-job
  interval: 1m
  chart:
   spec:
    chart: platforms/shared/charts/vault-k8s-mgmt
    sourceRef:
      kind: GitRepository
      name: flux-be-marr
      namespace: flux-be-marr
  values:
    metadata:
      name: smar-vaultk8s-job
      namespace: smar-bes
      images:
        alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
        pullPolicy: IfNotPresent

    vault:
      reviewer_service: vault-reviewer
      role: vault-role
      address: http://a94f258ac51304b63a9bceb42a204cb6-2100507752.eu-west-1.elb.amazonaws.com:20002
      authpath: besusmar
      policy: vault-crypto-smar-bes-smar-ro
      policydata: "{\n  \"policy\": \"path \\\"secretsv2/data/smar-bes/crypto/*\\\" {\n    capabilities = [\\\"read\\\", \\\"list\\\", \\\"create\\\", \\\"update\\\"]\n  }\n  path \\\"secretsv2/data/smar-bes/smartContracts/*\\\" {\n    capabilities = [\\\"read\\\", \\\"list\\\"]\n  }\"\n}"
      secret_path: secretsv2
      serviceaccountname: vault-auth
      imagesecretname: regcred

    k8s:
      kubernetes_url: https://C8FA1454BFC54EBEAC7D6A70501769F2.sk1.eu-west-1.eks.amazonaws.com
