apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: org-peer1
  namespace: org-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: org-peer1
  chart:
    git: https://github.com/mgCepeda/blockchain-automation-framework.git
    ref: fabric-email
    path: platforms/hyperledger-fabric/charts/peernode    
  values:
    metadata:
      namespace: org-net
      images:
        couchdb: couchdb:3.1
        peer: hyperledger/fabric-peer:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      pvc:
      deployment:
        
    peer:
      name: peer1
      gossippeeraddress: peer0.org-net:7051
      gossipexternalendpoint: peer1.org-net.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
      localmspid: orgMSP
      loglevel: info
      tlsstatus: true
      builder: hyperledger/fabric-ccenv:2.2.0
      couchdb:
        username: org-user

    storage:
      peer:
        storageclassname: orgsc
        storagesize: 512Mi
      couchdb:
        storageclassname: orgsc
        storagesize: 1Gi

    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: demoorg-net-auth
      secretprefix: secretsv2/data/crypto/peerOrganizations/org-net/peers/peer1.org-net
      secretambassador: secretsv2/data/crypto/peerOrganizations/org-net/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: secretsv2/data/credentials/org-net/couchdb/org?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: "haproxy"
      external_url_suffix: hf.dev2.aws.blockchaincloudpoc-develop.com
