apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mmar-expressapi
  namespace: mmar-ns
  annotations:
    fluxcd.io/automated: "false"
spec:
  chart:
    path: examples/supplychain-app/charts/expressapp
    git: "https://github.com/mgCepeda/blockchain-automation-framework.git"
    ref: "feature-1823"
  releaseName: mmarcorda-expressapi
  values:
    nodeName: mmar-expressapi
    metadata:
      namespace: mmar-ns
    replicaCount: 1
    expressapp:
      serviceType: ClusterIP
      image: adopblockchaincloud0502.azurecr.io/supplychain_corda:express_app_0.9.0.0
      pullPolicy: Always
      pullSecrets: regcred
      nodePorts:
        port: 3000
        targetPort: 3000
        name: tcp
      env:
        apiUrl: https://mmar-springboot.mmar-ns:20001/api/v1
    proxy:
      provider: ambassador
      name: mmar
      type: corda
      external_url_suffix: rc.dev2.aws.blockchaincloudpoc-develop.com
      peer_name: mmar
