apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mmar-springboot
  namespace: mmar-ns
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: mmar-springboot
  chart:
    path: examples/supplychain-app/charts/springbootwebserver
    git: "https://github.com/mgCepeda/blockchain-automation-framework.git"
    ref: "feature-1823"
  values:
    nodeName: mmar-springboot
    replicas: 1
    metadata:
      namespace: mmar-ns
      type: cordaopensource
    image:
      containerName: adopblockchaincloud0502.azurecr.io/supplychain_corda:springboot_0.9.0.0
      initContainerName: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
    smartContract:
      JAVA_OPTIONS : -Xmx512m
    volume:
      mountPath: /opt/corda
    nodeConf:
      node: mmar
      nodeRpcPort: 10003
      nodeRpcAdminPort: 10005
      controllerName: Controller
      trustStorePath: /opt/corda/certificates/sslkeystore.jks
      trustStoreProvider: jks
      legalName: O=Manufacturer,OU=Manufacturer,L=47.38/8.54/Zurich,C=CH
      devMode: false
      useHTTPS: true
      useSSL: false
      tlsAlias: cordaclienttls
      ssl:
        certificatesDirectory: na-ssl-false
        sslKeystoreFileName: na-ssl-false
        ssltruststore: na-ssl-false
    credentials:
      rpcUser: mmaroperations
    resources:
      limits: "512Mi"
      requests: "512Mi"
    storage:
      provisioner: kubernetes.io/aws-ebs
      memory: 512Mi
      name: awsstorageclass
      parameters:
        type: gp2
        encrypted: "true"
      annotations: {}
    web:
      targetPort: 20001
      port: 20001
    service:
      type: NodePort
      annotations: {}
    networkservices:
      networkmap: na
      doorman: na
    vault:
      address: "http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001"
      role: vault-role
      authpath: cordammar
      serviceaccountname: vault-auth
      rpcusersecretprefix: mmar/data/credentials/rpcusers
      keystoresecretprefix: mmar/data/credentials/keystore
      certsecretprefix: mmar/data/certs
    node:
      readinesscheckinterval: 10
      readinessthreshold: 15
    deployment:
      annotations: {}
    pvc:
      annotations: {}
