apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: notary2
  annotations:
    fluxcd.io/automated: "false"
  namespace: smar-ns
spec:
  releaseName: notary2
  chart:
    path: platforms/r3-corda/charts/notary
    git: https://github.com/mgCepeda/blockchain-automation-framework.git
    ref: feature-1823
  values:
    nodeName: notary2
    replicas: 1
    metadata:
      namespace: smar-ns
    image:
      containerName: adopblockchaincloud0502.azurecr.io/corda:4.7-linuxkit
      initContainerName: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
      doormanCertAlias: doormanmar.rc.dev2.aws.blockchaincloudpoc-develop.com
      networkmapCertAlias: networkmapmar.rc.dev2.aws.blockchaincloudpoc-develop.com
    nodeConf:
      p2p:
        url: notary2.smar-ns
        port: 10002
      ambassadorAddress: notary2.rc.dev2.aws.blockchaincloudpoc-develop.com:15021
      rpcSettings:
        useSsl: false
        standAloneBroker: false
        address: "0.0.0.0:10003"
        adminAddress: "0.0.0.0:10005"
        ssl:
          certificatesDirectory: na-ssl-false
          sslKeystorePath: na-ssl-false
          trustStoreFilePath: na-ssl-false
      legalName: O=Notary,OU=Notary,L=London,C=GB #use peer-node level subject for legalName
      messagingServerAddress:
      jvmArgs:
      systemProperties:
      sshd:
        port:
      exportJMXTo:
      transactionCacheSizeMegaBytes: 8
      attachmentContentCacheSizeMegaBytes: 10
      attachmentCacheBound: 1024
            
      notary:
        validating: True
        serviceLegalName: O=Notary Service,OU=Notary,L=London,C=GB
       
      detectPublicIp: false
      database:
        exportHibernateJMXStatistics: false
      dbUrl: notary2db
      dbPort: 9101
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dataSourceUrl: "jdbc:h2:tcp://notary2db:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
      jarPath: "/data/corda-workspace/h2/bin"
      networkMapURL: https://networkmapmar.rc.dev2.aws.blockchaincloudpoc-develop.com
      doormanURL: https://doormanmar.rc.dev2.aws.blockchaincloudpoc-develop.com
      compatibilityZoneURL:
      jarVersion: 4.7
      devMode: false
      env:
        - name: JAVA_OPTIONS
          value: -Xmx512m
        - name: CORDA_HOME
          value: /opt/corda
        - name: BASE_DIR
          value: /base/corda
    credentials:
      dataSourceUser: sa
      rpcUser:
        - name: notary2operations
          permissions: [ALL]

    cordapps:
      getcordapps: true
      jars:
        - url: https://alm.accenture.com/nexus/repository/AccentureBlockchainFulcrum_Release/com/supplychain/bcc/cordapp-supply-chain/4.7/cordapp-supply-chain-4.7.jar
        - url: https://alm.accenture.com/nexus/repository/AccentureBlockchainFulcrum_Release/com/supplychain/bcc/cordapp-contracts-states/4.7/cordapp-contracts-states-4.7.jar
        
    volume:
      baseDir: /base/corda
    resources:
      limits: "1Gi"
      requests: "1Gi" 
    pvc:
      name: notary2-pvc
      annotations: {}
      memory: 512Mi
      storageClassName: awsstorageclass

    service:
      name: notary2
      type: ClusterIP
      p2p:
        port: 10002
        targetPort: 10002
      rpc:
        port: 10003
        targetPort: 10003 
      rpcadmin:
        port: 10005
        targetPort: 10005
         
    deployment:
      annotations: {}
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      role: vault-role
      authpath: cordanotary2
      serviceaccountname: vault-auth
      dbsecretprefix: notary2/data/credentials/database
      rpcusersecretprefix: notary2/data/credentials/rpcusers
      keystoresecretprefix: notary2/data/credentials/keystore
      certsecretprefix: notary2/data/certs
      networkmapsecretprefix: notary2/data/credentials/networkmappassword
      cordappsreposecretprefix: notary2/data/credentials/cordapps
      retries: 10

          
    healthcheck:
      readinesscheckinterval: 20
      readinessthreshold: 20
    ambassador:
      component_name: notary2
      external_url_suffix: rc.dev2.aws.blockchaincloudpoc-develop.com
      p2p_ambassador: 15021
