apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: lotus-dev-net-ca-tools
  namespace: lotus-dev-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: lotus-dev-net-ca-tools
  chart:
    git: https://github.com/mgCepeda/blockchain-automation-framework.git
    ref: fabric-email
    path: platforms/hyperledger-fabric/charts/catools
  values:
    metadata:
      namespace: lotus-dev-net
      name: ca-tools
    replicaCount: 1

    image:
      repository: hyperledger/fabric-ca-tools
      tag: 1.2.1
      pullPolicy: IfNotPresent
      
    storage:
      storageclassname: lotus-devsc
      storagesize: 512Mi
