apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: channel-abc-dev-allchannel
  namespace: abc-dev-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: channel-abc-dev-allchannel
  chart:
    git: https://github.com/mgCepeda/blockchain-automation-framework.git
    ref: fabric-email
    path: platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: abc-dev-net
      network:
        version 2.2.2
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.abc-dev-net:7051
      localmspid: abc-devMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: devabc-dev-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/abc-dev-net/users/admin
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/abc-dev-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel
    orderer:
      address: orderer1.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
    channeltx: |-
      CtMDChgKFggCGgYIwMinjQYiCmFsbGNoYW5uZWwStgMKswMKCmFsbGNoYW5uZWwSQxIxCgtBcHBs
      aWNhdGlvbhIiEhAKDGxvdHVzLWRldk1TUBIAEg4KCmFiYy1kZXZNU1ASABoOCgpDb25zb3J0aXVt
      EgAa3wISswIKC0FwcGxpY2F0aW9uEqMCCAESDgoKYWJjLWRldk1TUBIAEhAKDGxvdHVzLWRldk1T
      UBIAGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMiLAoLRW5kb3JzZW1lbnQS
      HRITCAMSDwoLRW5kb3JzZW1lbnQQAhoGQWRtaW5zIjUKFExpZmVjeWNsZUVuZG9yc2VtZW50Eh0S
      EwgDEg8KC0VuZG9yc2VtZW50EAIaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMa
      BkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIO
      CAMSCgoGQWRtaW5zEAIaBkFkbWlucyoGQWRtaW5zGicKCkNvbnNvcnRpdW0SGRIXChVTdXBwbHlD
      aGFpbkNvbnNvcnRpdW0=