apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wmarwmarmember-node
  namespace: wmar-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: wmarwmarmember-node
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/node_besu
    sourceRef:
      kind: GitRepository
      name: flux-be-marr
      namespace: flux-be-marr
  values:
    metadata:
      namespace: wmar-bes
      labels:
    replicaCount: 1
    staticnodes:
      - "enode://f320a60873d2e9173bc48c018d090c310e3e568ad4bea7d2aae570ce8aee349bba2598a266ae0e02121a9e3bbb9e2bd1cabafc1322b235dc8a6a7934cd0b8820@validator1.bes.dev2.aws.blockchaincloudpoc-develop.com:15061"
      - "enode://6540b1e585cdf71aad0c2788096efa0cff4afbbebce61fa491cc6f2dd12e9b2436d65b2e8267c9c385de5b5c98e9a5c3f18d6b351d85f68fe00b2549537c60c8@validator2.bes.dev2.aws.blockchaincloudpoc-develop.com:15063"
      - "enode://405d5dfc285d480bad7f5ccafbba5cbaf30d558bf3fc97e08ce8af5e2cf61dc33f68ef51cced6cb9e124d969f663459da00298ed0320a17648fd12484a687566@cmar.bes.dev2.aws.blockchaincloudpoc-develop.com:15069"
      - "enode://6872dfcdd446e47cc6dd37ddcaa2b5e74e211e81395917be7c041a7a2ca8795ceffa879cb32026b228e84e658a305380ce745d1a193bb950271d3ecfc4aaf0f9@mmar.bes.dev2.aws.blockchaincloudpoc-develop.com:15065"
      - "enode://ce633b625324e5be90e3659ae1993d2c97aa357bada598fac1e0194a9c326bbad4dbdccd053a91ff8f1debffeedfcde33c1c2e07a59cc51c662c1ebe44897b2a@wmar.bes.dev2.aws.blockchaincloudpoc-develop.com:15067"
      - "enode://62948f8424975ab8db3d881e4efa27c8e8ce3888c3bbde89ec68bbfade034adae84973116f60e8d5234e749d87b8a41ab6aab40769528ed0759614784aa4530c@smar.bes.dev2.aws.blockchaincloudpoc-develop.com:15059"

    liveliness_check:
      enabled: false
    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5
    proxy:
      provider: ambassador
      external_url: wmar.bes.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15067
      rpc: 15068

    images:
      node: hyperledger/besu:22.10.2
      alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
      pullPolicy: IfNotPresent

    node:
      name: wmar
      consensus: qbft
      subject: O=Warehouse,OU=Warehouse,L=42.36/-71.06/Boston,C=US
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    tm:
      type: tessera
      tls: True
      url: "https://wmar-tessera.wmar-bes:8888"

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://a94f258ac51304b63a9bceb42a204cb6-2100507752.eu-west-1.elb.amazonaws.com:20002
      secretprefix: secretsv2/data/wmar-bes/crypto/wmar
      serviceaccountname: vault-auth
      keyname: data
      tmdir: tm
      tlsdir: tls
      role: vault-role
      authpath: besuwmar

    genesis: ewogICJjb25maWciIDogewogICAgImNoYWluSWQiIDogMjAxOCwKICAgICJjb25zdGFudGlub3BsZWZpeGJsb2NrIiA6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiIDogMjE0NzQ4MzY0NywKICAgICJxYmZ0IiA6IHsKICAgICAgImJsb2NrcGVyaW9kc2Vjb25kcyIgOiAyLAogICAgICAiZXBvY2hsZW5ndGgiIDogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiIDogMTAKICAgIH0KICB9LAogICJub25jZSIgOiAiMHgwIiwKICAidGltZXN0YW1wIiA6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiIDogIjB4MWZmZmZmZmZmZmZmZmYiLAogICJkaWZmaWN1bHR5IiA6ICIweDEiLAogICJleHRyYURhdGEiIDogIjB4ZjhhNGEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4N2U5NDhhY2RiNDQ5NGQ0MTRkZGQxMjg4N2Q5Zjg5NGM4ODBmNTQ4NTMzODk5NDNjODAyNzYyNjNiMjkwMzkxN2NiZGI5MDIwN2E1YjZjYTBiNTFmMDg5NGNlMTYxODEzYjYzNzMyNGM2YmJiMjYyYmIyMjQzMDNhMzQ4NTFjMDQ5NDIyNDlhMGQzMTc3MWMxMjU3NTMwMzZmNTc3OThkN2Q0NTQ3YjU4NTg5NGI5ODVhOGQ1NzMwNTI0YTgwZTUxMjc4ZDc5MzdlOWFkZmFjZWMxZWY5NDM3YmJmZDkwMTA0NGEyM2FiY2Q2OTEzNzlkOTc0NjdlY2MyMjMyZDRjMDgwYzAiCn0=
