apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: orderer6
  namespace: smari-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer6
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-mari
        namespace: flux-mari
      chart: platforms/hyperledger-fabric/charts/fabric-orderernode
  values:
    global:
      version: 2.2.2
      serviceAccountName: vault-auth
      cluster:
        provider: azure
        cloudNativeServices: false
      vault:
        type: hashicorp
        network: fabric
        address: http://98.64.226.131:20001
        authPath: marismari
        secretEngine: secretsv2
        secretPrefix: "data/marismari"
        role: vault-role
        tls: false
      proxy:
        provider: haproxy
        externalUrlSuffix: hlf.blockchaincloudpoc-develop.com

    storage:
      size: 512Mi
      reclaimPolicy: "Delete" 
      volumeBindingMode: 
      allowedTopologies:
        enabled: false

    certs:
      generateCertificates: true
      orgData:
        caAddress: ca.smari-net.hlf.blockchaincloudpoc-develop.com
        caAdminUser: smari-admin
        caAdminPassword: smari-adminpw
        orgName: smari
        type: orderer
        componentSubject: "O=Orderer,L=51.50/-0.13/London,C=GB"

      settings:
        createConfigMaps: False
        refreshCertValue: false
        addPeerValue: false
        removeCertsOnDelete: true
        removeOrdererTlsOnDelete: true

    image:
      orderer: ghcr.io/hyperledger/bevel-fabric-orderer
      alpineUtils: ghcr.io/hyperledger/bevel-alpine:latest
      pullSecret: ""

    orderer:
      consensus: raft
      logLevel: info
      localMspId: smariMSP
      tlsStatus: true
      keepAliveServerInterval: 10s
      serviceType: ClusterIP
      ports:
        grpc:
          clusterIpPort: 7050
        metrics: 
          enabled: False
          clusterIpPort: 9443
      resources:
        limits:
          memory: 512M
          cpu: 1
        requests:
          memory: 512M
          cpu: 0.25


    healthCheck: 
      retries: 10
      sleepTimeAfterError: 15

