apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: orderer-net-ca
  namespace: orderer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: orderer-net-ca
  chart:
    git: https://github.com/mgCepeda/blockchain-automation-framework.git
    ref: fabric-email
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    deployment:
      annotations:
    annotations:  
      service:
        - beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      pvc:
    metadata:
      namespace: orderer-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
    server:
      name: ca
      tlsstatus: true
      admin: orderer-admin
    storage:
      storageclassname: orderersc
      storagesize: 512Mi 
    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: demoorderer-net-auth
      secretcert: secretsv2/data/crypto/ordererOrganizations/orderer-net/ca?ca.orderer-net-cert.pem
      secretkey: secretsv2/data/crypto/ordererOrganizations/orderer-net/ca?orderer-net-CA.key
      secretadminpass: secretsv2/data/credentials/orderer-net/ca/orderer?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: haproxy
      type: orderer
      external_url_suffix: hf.dev2.aws.blockchaincloudpoc-develop.com
