---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Values.metadata.name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    {{- if $.Values.annotations }}
    {{- range $key, $value := $.Values.annotations.deployment }}
    {{- range $k, $v := $value }}
      {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- end }}
    {{- end }}     
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.metadata.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.metadata.name }}
    spec:
      serviceAccountName: {{ $.Values.vault.serviceaccountname }}
      imagePullSecrets:
        - name: {{ $.Values.vault.imagesecretname }}
      volumes:
      - name: ca-tools-pv
        persistentVolumeClaim:
          claimName: ca-tools-pvc
      - name: ca-tools-crypto-pv
        persistentVolumeClaim:
          claimName: ca-tools-crypto-pvc
      - name: certcheck
        emptyDir:
          medium: Memory
      - name: generate-crypto
        configMap:
          name: orderers-script-cm
          defaultMode: 0775
          items:
            - key: generate-crypto.sh
              path: generate-crypto.sh
      - name: generate-orderer-crypto
        configMap:
          name: orderers-script-cm
          defaultMode: 0775
          items:
            - key: orderer-script.sh
              path: orderer-script.sh
      - name: generate-user-crypto
        configMap:
          name: orderers-script-cm
          defaultMode: 0775
          items:
            - key: generate-user-crypto.sh
              path: generate-user-crypto.sh
      initContainers:
        - name: init-check-certificates
          image: {{ $.Values.initimage.alpineutils }}
          imagePullPolicy: IfNotPresent
          env:
          - name: VAULT_ADDR
            value: {{ $.Values.vault.address }}
          - name: VAULT_APP_ROLE
            value: {{ $.Values.vault.role }}
          - name: KUBERNETES_AUTH_PATH
            value: {{ $.Values.vault.authpath }}
          - name: VAULT_SECRET_MSP
            value: {{ $.Values.vault.secretmsp }}
          - name: VAULT_SECRET_ORDERER
            value: {{ $.Values.vault.secretorderer }}
          - name: COMPONENT_TYPE
            value: {{ $.Values.metadata.component_type }}
          - name: COMPONENT_NAME
            value: {{ $.Values.metadata.namespace }}
          - name: NAME
            value: {{ $.Values.metadata.org_name }}
          - name: ORDERERS_NAMES
            value: "{{ $.Values.orderers.name }}"
          - name: MOUNT_PATH
            value: "/certcheck"
          command: ["sh", "-c"]
          args:
            - |-
              #!/usr/bin/env sh
              validateVaultResponse () {
                if echo ${2} | grep "errors"; then
                  echo "ERROR: unable to retrieve ${1}: ${2}"
                  exit 1
                fi
                if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
                then
                  http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
                  --header "X-Vault-Token: ${VAULT_TOKEN}" \
                  ${VAULT_ADDR}/v1/${1})
                  curl_response=$?
                  if test "$http_code" != "200" ; then
                      echo "Http response code from Vault - $http_code and curl_response - $curl_response"
                      if test "$curl_response" != "0"; then
                        echo "Error: curl command failed with error code - $curl_response"
                        exit 1
                      fi
                  fi
                fi
              }

              # Setting up the environment to get secrets/certificates from Vault
              echo "Getting secrets/certificates from Vault server"
              KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
              VAULT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login -H "Content-Type: application/json" -d '{"role":"'"${VAULT_APP_ROLE}"'","jwt":"'"${KUBE_SA_TOKEN}"'"}' | jq -r 'if .errors then . else .auth.client_token end')
              validateVaultResponse 'vault login token' "${VAULT_TOKEN}"
              echo "Logged into Vault"
              
              mkdir -p ${MOUNT_PATH}
           
              # Check if certificates already present in the vault
              LOOKUP_SECRET_RESPONSE=$(curl --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${VAULT_SECRET_MSP} | jq -r 'if .errors then . else . end')

              if echo ${LOOKUP_SECRET_RESPONSE} | grep "errors"
              then
                echo "Certficates absent in vault. Ignore error warning"
                touch ${MOUNT_PATH}/absent_msp.txt
              elif echo ${LOOKUP_SECRET_RESPONSE} | grep "\"data\": null"
              then
                echo "Certficates absent in vault2. Ignore error warning"
                touch ${MOUNT_PATH}/absent_msp.txt
              else
                validateVaultResponse "${VAULT_SECRET_MSP}" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
                echo "Certificates present in vault"
                touch ${MOUNT_PATH}/present_msp.txt
              fi

              if [ $COMPONENT_TYPE == 'orderer' ] && [ -e /certcheck/absent_msp.txt ]; then
                  echo "meet the coditions"

                  OUTPUT_PATH="/crypto-config/${COMPONENT_TYPE}Organizations/${COMPONENT_NAME}"
                  mkdir -p ${OUTPUT_PATH}/ca
                  mkdir -p /root/ca-tools/${NAME}
  
                  SECRET_CERT={{ $.Values.vault.secretcert }}
                  vault_secret_key=$(echo ${SECRET_CERT} |awk -F "?" '{print $1}')
                  vault_data_key=$(echo ${SECRET_CERT} |awk -F "?" '{print $2}')
              
                  LOOKUP_SECRET_RESPONSE=$(curl -sS \
                      --header "X-Vault-Token: ${VAULT_TOKEN}" \
                      ${VAULT_ADDR}/v1/${vault_secret_key} | \
                      jq -r 'if .errors then . else . end')
                  validateVaultResponse "${vault_secret_key}" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
                  VALUE_OF_SECRET=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r ".data.data[\"${vault_data_key}\"]")
                  echo "${VALUE_OF_SECRET}" >> ${OUTPUT_PATH}/ca/ca.${COMPONENT_NAME}-cert.pem
              fi;
              if [ $COMPONENT_TYPE == 'orderer' ]; then

                  orderers=$(echo "$ORDERERS_NAMES" | tr "-" "\n")

                  for ORDERER_NAME in $orderers
                  do
                   
                      # Check if certificates already present in the vault
                      LOOKUP_SECRET_RESPONSE=$(curl --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${VAULT_SECRET_ORDERER}/${ORDERER_NAME}.${COMPONENT_NAME}/msp | jq -r 'if .errors then . else . end')

                      if echo ${LOOKUP_SECRET_RESPONSE} | grep "errors"
                      then
                        echo "Certficates absent in vault. Ignore error warning"
                        touch ${MOUNT_PATH}/absent_msp_${ORDERER_NAME}.txt
                      elif echo ${LOOKUP_SECRET_RESPONSE} | grep "\"data\": null"
                      then
                        echo "Certficates absent in vault2. Ignore error warning"
                        touch ${MOUNT_PATH}/absent_msp_${ORDERER_NAME}.txt
                      else
                        validateVaultResponse "${VAULT_ADDR}/v1/${VAULT_SECRET_ORDERER}/${ORDERER_NAME}.${COMPONENT_NAME}/msp" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
                        echo "Certificates present in vault"
                        touch ${MOUNT_PATH}/present_msp_${ORDERER_NAME}.txt
                      fi

                      # Check if certificates already present in the vault
                      LOOKUP_SECRET_RESPONSE=$(curl --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${VAULT_SECRET_ORDERER}/${ORDERER_NAME}.${COMPONENT_NAME}/tls | jq -r 'if .errors then . else . end')

                      if echo ${LOOKUP_SECRET_RESPONSE} | grep "errors"
                      then
                        echo "Certficates absent in vault. Ignore error warning"
                        touch ${MOUNT_PATH}/absent_tls_${ORDERER_NAME}.txt
                      elif echo ${LOOKUP_SECRET_RESPONSE} | grep "\"data\": null"
                      then
                        echo "Certficates absent in vault2. Ignore error warning"
                        touch ${MOUNT_PATH}/absent_tls_${ORDERER_NAME}.txt
                      else
                        validateVaultResponse "${VAULT_ADDR}/v1/${VAULT_SECRET_ORDERER}/${ORDERER_NAME}.${COMPONENT_NAME}/tls" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
                        echo "Certificates present in vault"
                        touch ${MOUNT_PATH}/present_tls_${ORDERER_NAME}.txt
                      fi    
                  done

              fi;

          volumeMounts:
          - name: ca-tools-pv
            mountPath: /root/ca-tools
          - name: ca-tools-crypto-pv
            mountPath: /crypto-config
          - name: certcheck
            mountPath: /certcheck
      containers:
        - name: {{ .Values.metadata.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: VAULT_ADDR
            value: {{ $.Values.vault.address }}
          - name: VAULT_APP_ROLE
            value: {{ $.Values.vault.role }}
          - name: KUBERNETES_AUTH_PATH
            value: {{ $.Values.vault.authpath }}
          - name: VAULT_SECRET_MSP
            value: {{ $.Values.vault.secretmsp }}
          - name: VAULT_SECRET_TLS
            value: {{ $.Values.vault.secrettls }}
          - name: COMPONENT_TYPE
            value: {{ $.Values.metadata.component_type }}
          - name: COMPONENT_NAME
            value: {{ $.Values.metadata.namespace }}
          - name: NAME
            value: {{ $.Values.metadata.org_name }}
          - name: PROXY
            value: {{ .Values.metadata.proxy }}
          - name: EXTERNAL_URL_SUFFIX
            value: {{ .Values.item.external_url_suffix }}
          - name: ORDERERS_NAMES
            value: "{{ $.Values.orderers.name }}"
          - name: ROOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: roottoken
                key: token
          command: ["sh", "-c", "/bin/bash"]
          args:
            - |-

                echo "Run generate-crypto.sh"
                cd /root/ca-tools/${NAME} 
                cat generate-crypto.sh

              tail -f /dev/null
          volumeMounts:
          - name: ca-tools-pv
            mountPath: /root/ca-tools
          - name: ca-tools-crypto-pv
            mountPath: /crypto-config
          - name: certcheck
            mountPath: /certcheck
          - name: generate-crypto
            mountPath: /root/ca-tools/{{ $.Values.metadata.org_name }}/generate-crypto.sh
            subPath: generate-crypto.sh
          - name: generate-orderer-crypto
            mountPath: /root/ca-tools/{{ $.Values.metadata.org_name }}/orderer-script.sh
            subPath: orderer-script.sh
          - name: generate-user-crypto
            mountPath: /root/ca-tools/{{ $.Values.metadata.org_name }}/generate-user-crypto.sh
            subPath: generate-user-crypto.sh
