apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: channel-cmar-allchannel
  namespace: cmar-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: channel-cmar-allchannel
  chart:
    git: https://github.com/mgCepeda/blockchain-automation-framework.git
    ref: feature-1572
    path: platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: cmar-net
      network:
        version 2.2.2
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.cmar-net:7051
      localmspid: cmarMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9001
      authpath: demo-testcmar-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/cmar-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/cmar-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel
    orderer:
      address: orderer1.hf.demo.aws.blockchaincloudpoc-develop.com:8443
    channeltx: |-
      CqkDChgKFggCGgYItqL6hwYiCmFsbGNoYW5uZWwSjAMKiQMKCmFsbGNoYW5uZWwSLhIcCgtBcHBs
      aWNhdGlvbhINEgsKB2NtYXJNU1ASABoOCgpDb25zb3J0aXVtEgAaygISngIKC0FwcGxpY2F0aW9u
      Eo4CCAESCwoHY21hck1TUBIAGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMi
      NQoUTGlmZWN5Y2xlRW5kb3JzZW1lbnQSHRITCAMSDwoLRW5kb3JzZW1lbnQQAhoGQWRtaW5zIiIK
      B1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3Jp
      dGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiwKC0VuZG9y
      c2VtZW50Eh0SEwgDEg8KC0VuZG9yc2VtZW50EAIaBkFkbWlucyoGQWRtaW5zGicKCkNvbnNvcnRp
      dW0SGRIXChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0=