##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Build Supplychain-App fabric docker images triggered by :
#  - push on develop branch for latest tags 
#  - create tag vx.y.z for release tags
#  - Can be triggered manually

name: Build Supplychain App Corda Images

on:
  workflow_dispatch:
  create:
    tags:
      - v*
  push:
    branches:
      - feature-1823 #change to developD
    paths:
      - 'examples/supplychain-app/corda/**'
      - '.github/workflows/corda_supplychain_images_build.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_PATH: ghcr.io/${{ github.repository_owner }}

jobs:
  # on push to develop branch, create docker tags latest
  corda-latest:
    if: ${{ startsWith(github.ref, 'refs/heads/feature-1823') }} #change to develop
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
    
    - name: Run Testss
      run: |
        WDIR=`pwd`
        
        java -version
        update-alternatives --list java

        echo "---- building networkmap ----"
        cd ${WDIR}/examples/supplychain-app/corda/cordApps_springBoot
        ls
        echo "---- finish ----"

    - run: pwd
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Login to the container registry
      uses: docker/login-action@v1
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Lowercase IMAGE_PATH
      id: image_path_format
      uses: ASzc/change-string-case-action@v2
      with:
        string: ${{ env.IMAGE_PATH }}
       
    - name: Build and push supplychain app latest
      id: corda_express_latest
      uses: docker/build-push-action@v2
      with:
        context: examples/supplychain-app/corda/express_nodeJS
        push: true
        tags: ${{ steps.image_path_format.outputs.lowercase }}/bevel-supplychain-corda:express-app-latest

    - name: Build and push supplychain rest-serverr
      id: corda_supplychain_latest
      uses: docker/build-push-action@v2
      with:
        context: examples/supplychain-app/corda/cordApps_springBoot
        push: true
        tags: ${{ steps.image_path_format.outputs.lowercase }}/bevel-supplychain-corda:cordApps-springBoot-latest

  # quorum-release: 
  #   if: ${{ startsWith(github.ref, 'refs/tags/v') }}
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2

  #   - name: Set output
  #     id: vars
  #     run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}
    
  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v1
    
  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v1
    
  #   - name: Login to the container registry
  #     uses: docker/login-action@v1
  #     with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #   - name: Build and push supplychain app release
  #     id: quorum_supplychain_release
  #     uses: docker/build-push-action@v2
  #     with:
  #       context: examples/supplychain-app/quorum/express_nodeJS
  #       push: true
  #       tags: ${{ env.IMAGE_PATH }}/bevel-supplychain-quorum:express-app-${{ steps.vars.outputs.tag }},${{ env.IMAGE_PATH }}/bevel-supplychain-quorum:express-app-stable
