##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

#############################################################################################
# This role creates the block modification script for system channel.
#############################################################################################

############################################################################################
# This task creates the generate_block.sh file for new organizations
- name: "Create create-syschannel-block.sh script file for new orderer"
  template:
    src: "syschannel_update_consenter_script.tpl"
    dest: "{{ build_path }}/syschannel-update-script.sh"
  vars:
    component_name: "{{ org.name | lower }}"
    os: "{{ fabric.os }}"
    arch: "{{ fabric.arch }}"
    version: "{{ network.version }}"
    orderer_name: "{{ orderer.name | lower }}"
    namespace: "{{ component_ns }}"

############################################################################################
# This task calls nested_create_cli to generate the cli value files for the orderer organization
- name: Call nested_create_cli for the first orderer
  include_tasks: nested_create_cli.yaml
  vars:
    orderer: "{{ org.services.orderers | first }}"

# # This task creates the genesis block by consuming the latest config block
# - name: "Create genesis block"
#   shell: |
#     cat {{ build_path }}/{{ channel_name }}_config_block.pb | base64 > {{ build_path }}/channel-artifacts/genesis.block.base64
#   when: update_type == "tls"
#   tags:
#     - molecule-idempotence-notest

# # add new genesis block to the vault
# - name: "Write genesis block to Vault"  
#   shell: |
#     vault kv put {{ org.vault.secret_path | default('secretsv2') }}/crypto/ordererOrganizations/{{ component_ns }}  {{ network.env.type }}GenesisBlock="$(cat {{build_path}}/channel-artifacts/genesis.block.base64)"
#   environment:
#     VAULT_ADDR: "{{ org.vault.url }}"
#     VAULT_TOKEN: "{{ org.vault.root_token }}"
#   tags:
#     - molecule-idempotence-notest
